feeds:
  - https://feeds.bbci.co.uk/news/world/rss.xml
  - https://www.aljazeera.com/xml/rss/all.xml
  - https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945    # DoD news (general)
  - https://feeds.bloomberg.com/markets/news.rss
  - https://www.ft.com/news-feed?format=rss
  - https://www.sec.gov/news/pressreleases.rss
  - https://www.state.gov/rss-feed/press-releases/feed/
  - https://www.consilium.europa.eu/en/rss/pressreleases.ashx/
  - https://www.imf.org/en/News/rss
