feeds:
  - https://feeds.bbci.co.uk/news/world/rss.xml
  - https://www.aljazeera.com/xml/rss/all.xml
  - https://www.defense.gov/DesktopModules/ArticleCS/RSS.ashx?ContentType=1&Site=945    # DoD news (general)
