# Minimal first-pass rules. Tweak freely.
kinetic_keywords:
  - airstrike
  - missile
  - drone
  - artillery
  - bombardment
  - shelling
  - rocket
  - strike
  - clashes
  - offensive
  - attack
  - bombard
  - bombardment
  - mobilization
  - incursion
  - invasion
casualty_keywords:
  - killed
  - dead
  - casualties
  - wounded
  - injured
market_impact_keywords:
  - downgrade
  - credit watch
  - CDS
  - yield surge
  - bond issuance
  - rating action
  - capital controls
commerce_disruption_keywords:
  - shipping
  - closure
  - airspace
  - embargo
  - blockade
  - insurance
  - reroute
  - port
  - sanctions
  - export control
  - OFAC
  - EU Council restrictive measures
  - entity list
  - SDN list
  - embargo
  - tariff
  - price cap
  - secondary sanctions
  - general license
  - export ban
regions:
  - Black Sea
  - Red Sea
  - Taiwan Strait
  - Sahel
  - Gaza
  - Donbas
  - Crimea
  - Nagorno-Karabakh
  - South China Sea
  - Horn of Africa
  - Baltics
  - Persian Gulf
  procurement_keywords:
  - appropriation
  - defense budget
  - supplemental spending
  - NDAA
  - procurement
  - tender
  - RFP
  - contract award
  - arms deal
source_tiers:        # crude credibility weighting (domain contains key)
  tier3:
    - bbc.co.uk
    - bbc.com
    - reuters.com
    - apnews.com
    - defense.gov
  tier2:
    - aljazeera.com
    - theguardian.com
    - ft.com
  tier1:
    - medium.com
    - blogspot.com
